module.exports = {
  PARSEERROR: 'TORTOISE.PARSEERROR',
  CONNECTIONDISCONNECTED: 'TORTOISE.CONNECTIONDISCONNECTED',
  CONNECTIONCLOSED: 'TORTOISE.CONNECTIONCLOSED',
  CONNECTIONERROR: 'TORTOISE.CONNECTIONERROR'
}